### ISSUE TITLE
How to config exclusive=true ?

### ISSUE THREAD

**Issue by wcc526** [mozes/stompest#8]
http://activemq.apache.org/exclusive-consumer.html

java code is 

```
   queue = new ActiveMQQueue("TEST.QUEUE?consumer.exclusive=true");
   consumer = session.createConsumer(queue);
```

I have try to config uri

failover:(tcp://xxxx:61613,tcp://xxx)?exclusive=true,randomize=false,maxReconnectDelay=30000

there is a errror:

[invalid options: 'exclusize']
Exception AttributeError: "'ActiveMQConsumer' object has no attribute 'client'" in <bound method

**Comment by theduderog** [comment]
I don't know.  I'm not maintaining this library any more.  Please check the [new project home](https://github.com/nikipore/stompest).
